export type PostType = 'NEWS' | 'RECIPE'

/** content is sanitized HTML from the admin editor (older posts may still be plain text — render via toPostHtml). */
export interface Post {
  id: string
  title: string
  slug: string
  excerpt: string | null
  content: string
  coverImageUrl: string | null
  type: PostType
  categoryId: string | null
  /** Included on list rows and the public detail endpoint; absent on the admin single-post GET. */
  category?: PostCategoryRef | null
  isPublished: boolean
  publishedAt: string | null
  createdAt: string
  updatedAt: string
}

/** List rows (GET /api/posts and /api/admin/posts) omit the (potentially large) HTML body. */
export type PostListItem = Omit<Post, 'content'>

export interface PostCategoryRef {
  id: string
  name: string
  slug: string
  isActive?: boolean
}

/** A "Góc Biển" post category. postCount counts published posts only on the storefront (activeOnly) listing. */
export interface PostCategory {
  id: string
  name: string
  slug: string
  description: string | null
  imageUrl: string | null
  isActive: boolean
  position: number
  postCount: number
}

export interface BannerButton {
  id: string
  label: string
  link: string
  position: number
}

export interface Banner {
  id: string
  imageUrl: string | null
  title: string | null
  subtitle: string | null
  buttons: BannerButton[]
  position: number
  isActive: boolean
}

/** Iconify (simple-icons) presets offered in the admin icon picker — no extra npm dependency needed. */
export const SOCIAL_ICON_PRESETS = [
  { key: 'facebook', label: 'Facebook', icon: 'i-simple-icons-facebook' },
  { key: 'instagram', label: 'Instagram', icon: 'i-simple-icons-instagram' },
  { key: 'threads', label: 'Threads', icon: 'i-simple-icons-threads' },
  { key: 'tiktok', label: 'TikTok', icon: 'i-simple-icons-tiktok' },
  { key: 'messenger', label: 'Messenger', icon: 'i-simple-icons-messenger' },
  { key: 'zalo', label: 'Zalo', icon: 'i-simple-icons-zalo' },
  { key: 'youtube', label: 'YouTube', icon: 'i-simple-icons-youtube' },
  { key: 'telegram', label: 'Telegram', icon: 'i-simple-icons-telegram' },
  { key: 'shopee', label: 'Shopee', icon: 'i-simple-icons-shopee' },
] as const

export type SocialLinkIconType = 'PRESET' | 'CUSTOM'
export type SocialLinkDisplay = 'FOOTER' | 'FIXED'
export type SocialLinkSize = 'SMALL' | 'MEDIUM' | 'LARGE' | 'XLARGE' | 'XXLARGE'

/**
 * Container/icon pixel sizes per tier — MEDIUM matches the storefront's fixed scroll-to-top
 * button. Plain px numbers applied via inline style, not Tailwind classes: a size class used
 * nowhere else as a literal string (e.g. "size-13") never gets generated by Tailwind's content
 * scanner since this file lives outside the scanned app/ directories, silently leaving the
 * element unsized.
 */
export const SOCIAL_ICON_SIZES = [
  { key: 'SMALL', label: 'Nhỏ', box: 28, icon: 14 },
  { key: 'MEDIUM', label: 'Vừa', box: 36, icon: 20 },
  { key: 'LARGE', label: 'Lớn', box: 44, icon: 24 },
  { key: 'XLARGE', label: 'Rất lớn', box: 52, icon: 28 },
  { key: 'XXLARGE', label: 'Cực lớn', box: 60, icon: 32 },
] as const

export interface SocialLink {
  id: string
  label: string | null
  url: string
  iconType: SocialLinkIconType
  iconKey: string | null
  imageUrl: string | null
  /** FOOTER: shown in the storefront footer row (default). FIXED: floating button on the right edge of every page. */
  displayLocation: SocialLinkDisplay
  size: SocialLinkSize
  position: number
  isActive: boolean
}
