name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          timeout: 30m
          command_timeout: 30m
          script: |
            cd /opt/ca-nha-bien

            git pull origin main

            docker compose build app

            docker compose up -d

            docker compose exec -T app npx prisma migrate deploy

            docker image prune -f
            docker builder prune -f --filter "until=48h"
